# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='profiles',
        ),
    ]
