# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_auto_20200819_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, related_name='profile_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
