# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profiles',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
